#!/bin/bash

sudo apt install postgresql postgresql-contrib -y

# Create database and user
sudo -i -u postgres psql -c "CREATE DATABASE mydatabase;"
sudo -i -u postgres psql -c "CREATE USER mydbuser WITH PASSWORD 'MyDBPassword';"
sudo -i -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE mydatabase TO mydbuser;"

# Configure PostgreSQL to accept remote connections
echo "host    all             all             0.0.0.0/0               md5" | sudo tee -a /etc/postgresql/14/main/pg_hba.conf

# Ensure the correct path for postgresql.conf
sudo sed -i "s/^#listen_addresses = 'localhost'/listen_addresses = '*'/g" /etc/postgresql/14/main/postgresql.conf

# Restart PostgreSQL service
sudo systemctl restart postgresql

# Create table and insert data
sudo -u postgres psql -d mydatabase -c "CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, first_name TEXT NOT NULL, last_name TEXT NOT NULL);"
sudo -u postgres psql -d mydatabase -c "INSERT INTO users (first_name, last_name) VALUES ('Colton', 'Dixon');"
sudo -u postgres psql -d mydatabase -c "INSERT INTO users (first_name, last_name) VALUES ('John', 'Doe');"
sudo -u postgres psql -d mydatabase -c "GRANT ALL PRIVILEGES ON TABLE users TO mydbuser;"

#Firewall Rules
sudo ufw allow from 10.0.1.4 to any port 5432
sudo ufw allow proto tcp from 10.0.1.5 to any port 22
sudo ufw enable

# Install AppArmor
sudo apt-get update
sudo apt-get install -y apparmor-profiles apparmor-utils

# Create AppArmor profile directory if not exists
sudo mkdir -p /etc/apparmor.d

# Create the AppArmor profile file
sudo tee /etc/apparmor.d/usr.lib.postgresql.14.bin.postgres <<EOT
#include <tunables/global>

# profile definition for PostgreSQL 14
/usr/lib/postgresql/14/bin/postgres {
  #include <abstractions/base>
  #include <abstractions/nameservice>

  /etc/postgresql/** r,
  /usr/share/postgresql/** r,
  /var/lib/postgresql/** rwl,
  /{,var/}run/postgresql/** rw,
  owner @{PROC}/14/oom_adj rw,
}
EOT

# Apply the AppArmor profile
sudo apparmor_parser -r -W /etc/apparmor.d/usr.lib.postgresql.14.bin.postgres

# Ensure AppArmor service is enabled and start the service
sudo systemctl enable apparmor
sudo systemctl start apparmor

# Enforce the profile
sudo aa-enforce /etc/apparmor.d/usr.lib.postgresql.14.bin.postgres

