#!/bin/bash

# Enable IP forwarding
echo "net.ipv4.ip_forward=1" | sudo tee -a /etc/sysctl.conf

# Apply changes
sudo sysctl -p

#Restart Networking
sudo netplan apply

sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j DNAT --to-destination 10.0.1.4:80
sudo iptables -t nat -A POSTROUTING -p tcp -d 10.0.1.4 --dport 80 -j MASQUERADE

sudo iptables-save > /etc/iptables/rules.v4

sudo apt-get install iptables-persistent
