- name: Create Azure VM
  hosts: localhost
  connection: local

  vars_prompt:
   - name: "resource_group"
     prompt: "Please name the deployment"

  vars:
    username: "azureadmin"
    password: "SecurePassword123"
    resourcegroup: 
  tasks:

  - name: Create resource group
    azure_rm_resourcegroup:
      name: "{{ resource_group}}"
      location: westus2
      state: present

  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: "{{ resource_group}}"
      name: ControlPlane-Vnet
      address_prefixes: "10.0.0.0/16"
      state: present

  - name: Add subnet
    azure_rm_subnet:
      resource_group: "{{ resource_group}}"
      name: Ansible-Subnet
      address_prefix: "10.0.0.0/24"
      virtual_network: ControlPlane-Vnet
      state: present

  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: "{{ resource_group}}"
      name: Ansible-RG
      state: present

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group}}"
      allocation_method: Static
      name: Web-IP

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ resource_group}}"
      allocation_method: Static
      name: DB-IP

  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ resource_group}}"
      name: VM01-NIC
      virtual_network: ControlPlane-Vnet
      subnet: Ansible-Subnet
      security_group: Ansible-RG
      ip_configurations:
        - name: ipconfig1
          private_ip_address: 10.0.0.4 
          private_ip_allocation_method: Static
          public_ip_address_name: Web-IP
      state: present

  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: "{{ resource_group}}"
      name: VM02-NIC
      virtual_network: ControlPlane-Vnet
      subnet: Ansible-Subnet
      security_group: Ansible-RG
      ip_configurations:
        - name: ipconfig1
          private_ip_address: 10.0.0.5 
          private_ip_allocation_method: Static
          public_ip_address_name: DB-IP
      state: present

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group}}"
      name: WebVM
      vm_size: Standard_DS1_v2
      admin_username: "{{ username }}"
      managed_disk_type: Standard_LRS
      ssh_password_enabled: true
      admin_password: "{{ password }}"
      network_interfaces: VM01-NIC
      image:
        offer: 0001-com-ubuntu-server-jammy
        publisher: Canonical
        sku: 22_04-lts
        version: latest
      boot_diagnostics:
        enabled: true
        type: managed

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group}}"
      name: DB-VM
      vm_size: Standard_DS1_v2
      admin_username: "{{ username }}"
      managed_disk_type: Standard_LRS
      ssh_password_enabled: true
      admin_password: "{{ password }}"
      network_interfaces: VM02-NIC
      image:
        offer: 0001-com-ubuntu-server-jammy
        publisher: Canonical
        sku: 22_04-lts
        version: latest
      boot_diagnostics:
        enabled: true
        type: managed
