---
- name: WebVM-Deploy
  hosts: web
  become: yes

  tasks:
    - name: Install python3-pip and nginx
      apt:
        name:
          - python3-pip
          - nginx
        state: present
        update_cache: yes

    - name: Install psycopg2-binary with pip
      pip:
        name: psycopg2-binary
        executable: pip3

    - name: Install Flask with pip
      pip:
        name: flask
        executable: pip3

    - name: Stop nginx service
      service:
        name: nginx
        state: stopped

    - name: Remove default site-enabled configuration
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Remove default site-available configuration
      file:
        path: /etc/nginx/sites-available/default
        state: absent

    - name: Curl Nginx Configuration from Github
      shell: curl -o /etc/nginx/sites-available/default https://raw.githubusercontent.com/ColtonDx/Mentorship/refs/heads/main/nginx
      args:
        creates: /etc/nginx/sites-available/default

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /myapp
        - /myapp/templates

    - name: Download App.py
      shell:  curl -o /myapp/app.py https://raw.githubusercontent.com/ColtonDx/Mentorship/refs/heads/main/app.py
      args:
        creates: /myapp/app.py

    - name: Download Index.html
      shell: curl -o /myapp/templates/index.html https://raw.githubusercontent.com/ColtonDx/Mentorship/refs/heads/main/index.html
      args:
        creates: /myapp/templates/index.html

    - name: Download Index.html
      shell: curl -o /etc/systemd/system/flask-app.service https://raw.githubusercontent.com/ColtonDx/Mentorship/refs/heads/main/flask-app.service
      args:
        creates: /etc/systemd/system/flask-app.service

    - name: Enable Flask Service
      systemd:
        name: flask-app
        enabled: yes

    - name: Start Flask
      systemd:
        name: flask-app
        state: started

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
